#!/bin/bash

# Directory of the current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Path to your Python script, relative to the current script's directory
PYTHON_SCRIPT="$DIR/rpm2cpio.py"

# Pass all arguments to the Python script
python "$PYTHON_SCRIPT" "$@"